# Generated by Django 4.2.3 on 2026-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
